"""
Claude Integration Generator

Generates CLAUDE.md and .claude/skills/ files for user repositories
to enable efficient drift remediation using Claude Code CLI.
"""

from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

from api_contract_validator.analysis.drift.models import (
    ContractDriftIssue,
    DriftReport,
    ValidationDriftIssue,
)
from api_contract_validator.analysis.reasoning.models import AnalysisResult
from api_contract_validator.config.logging import get_logger
from api_contract_validator.config.models import Config

logger = get_logger("api_contract_validator.claude_integration")


class ClaudeIntegrationGenerator:
    """
    Generates Claude Code CLI integration files for user repositories.
    """

    def __init__(self, config: Config):
        """
        Initialize Claude integration generator.

        Args:
            config: Application configuration
        """
        self.config = config

    def generate(
        self,
        drift_report: DriftReport,
        analysis_result: Optional[AnalysisResult],
        spec_path: Path,
    ) -> Dict[str, Path]:
        """
        Generate Claude Code integration files.

        Args:
            drift_report: Drift detection results
            analysis_result: Optional AI analysis results
            spec_path: Path to OpenAPI specification

        Returns:
            Dictionary mapping file type to generated file path
        """
        logger.info("Generating Claude Code integration files")

        # Find repo root
        repo_root = self._find_repo_root(spec_path)
        logger.info(f"Detected repo root: {repo_root}")

        generated_files = {}

        # Generate CLAUDE.md
        claude_md_path = self._generate_claude_md(
            drift_report, analysis_result, repo_root, spec_path
        )
        generated_files["claude_md"] = claude_md_path

        # Generate skills
        skills_dir = repo_root / ".claude" / "skills"
        skills_dir.mkdir(parents=True, exist_ok=True)

        if drift_report.validation_drift:
            skill_path = self._generate_fix_validation_skill(
                drift_report, analysis_result, skills_dir
            )
            generated_files["fix_validation_skill"] = skill_path

        if drift_report.contract_drift:
            skill_path = self._generate_fix_contract_skill(
                drift_report, analysis_result, skills_dir
            )
            generated_files["fix_contract_skill"] = skill_path

        if analysis_result and analysis_result.remediations:
            skill_path = self._generate_apply_remediations_skill(
                analysis_result, skills_dir, drift_report
            )
            generated_files["apply_remediations_skill"] = skill_path

        logger.info(f"Generated {len(generated_files)} Claude integration files")
        return generated_files

    def _find_repo_root(self, spec_path: Path) -> Path:
        """
        Find the repository root directory.

        Strategy:
        1. Look for .git directory in parent hierarchy
        2. Fall back to spec file's parent directory

        Args:
            spec_path: Path to OpenAPI specification

        Returns:
            Path to repository root
        """
        current = spec_path.parent.absolute()

        # Search for .git directory
        for parent in [current] + list(current.parents):
            if (parent / ".git").exists():
                return parent

        # Fallback to spec directory
        return current

    def _generate_claude_md(
        self,
        drift_report: DriftReport,
        analysis_result: Optional[AnalysisResult],
        repo_root: Path,
        spec_path: Path,
    ) -> Path:
        """
        Generate CLAUDE.md with project-specific guidance.

        Args:
            drift_report: Drift detection results
            analysis_result: Optional AI analysis
            repo_root: Repository root path
            spec_path: OpenAPI spec path

        Returns:
            Path to generated CLAUDE.md
        """
        timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

        content = f"""# API Drift Remediation Guide

**Last Updated:** {timestamp}
**Generated by:** API Contract Validator

---

## Project Context

- **API Specification:** `{spec_path.relative_to(repo_root) if spec_path.is_relative_to(repo_root) else spec_path}`
- **Total Drift Issues:** {drift_report.summary.total_issues}
- **Affected Endpoints:** {len(drift_report.summary.affected_endpoints)}
- **Validation Date:** {timestamp}

### Drift Summary

| Severity | Count |
|----------|-------|
| Critical | {drift_report.summary.critical_count} 🔴 |
| High | {drift_report.summary.high_count} 🟠 |
| Medium | {drift_report.summary.medium_count} 🟡 |
| Low | {drift_report.summary.low_count} ⚪ |

### Drift by Type

- **Contract Drift:** {len(drift_report.contract_drift)} issues (response schema mismatches)
- **Validation Drift:** {len(drift_report.validation_drift)} issues (accepts invalid inputs)
- **Behavioral Drift:** {len(drift_report.behavioral_drift)} issues (inconsistent behavior)

---

## Critical Issues Requiring Immediate Attention

"""

        # Add validation drift section
        if drift_report.validation_drift:
            high_validation = [
                issue for issue in drift_report.validation_drift if issue.severity == "high"
            ]
            if high_validation:
                content += f"""### Validation Drift ({len(high_validation)} HIGH severity)

Your API accepts invalid inputs that should be rejected. This poses security and data integrity risks.

**Affected Endpoints:**
"""
                affected_endpoints = set(issue.endpoint_id for issue in high_validation)
                for endpoint in sorted(affected_endpoints):
                    endpoint_issues = [i for i in high_validation if i.endpoint_id == endpoint]
                    content += f"- `{endpoint}` ({len(endpoint_issues)} issues)\n"

                content += "\n**Common Violations:**\n"
                constraint_types = {}
                for issue in high_validation[:10]:  # Top 10
                    constraint = issue.violated_constraint.split(":")[0]
                    constraint_types[constraint] = constraint_types.get(constraint, 0) + 1

                for constraint, count in sorted(
                    constraint_types.items(), key=lambda x: x[1], reverse=True
                ):
                    content += f"- {constraint} ({count} occurrences)\n"

                content += "\n**Recommended Action:** Add input validation middleware. See `.claude/skills/fix-validation-drift.md`\n\n"

        # Add contract drift section
        if drift_report.contract_drift:
            high_contract = [
                issue for issue in drift_report.contract_drift if issue.severity == "high"
            ]
            if high_contract:
                content += f"""### Contract Drift ({len(high_contract)} HIGH severity)

API responses don't match the OpenAPI specification schema.

**Affected Endpoints:**
"""
                affected_endpoints = set(issue.endpoint_id for issue in high_contract)
                for endpoint in sorted(affected_endpoints):
                    content += f"- `{endpoint}`\n"

                content += "\n**Recommended Action:** Fix response serializers. See `.claude/skills/fix-contract-drift.md`\n\n"

        # Add AI analysis insights if available
        if analysis_result:
            content += f"""---

## AI Analysis Insights

{analysis_result.executive_summary}

"""
            if analysis_result.systemic_issues:
                content += "### Systemic Issues\n\n"
                for issue in analysis_result.systemic_issues:
                    content += f"- {issue}\n"
                content += "\n"

            if analysis_result.root_causes:
                content += f"### Root Cause Analysis\n\n"
                content += f"Found {len(analysis_result.root_causes)} root cause(s). See detailed report for full analysis.\n\n"

            if analysis_result.remediations:
                content += f"### Available Remediations\n\n"
                content += f"AI generated {len(analysis_result.remediations)} specific remediation suggestion(s).\n"
                content += "Use `.claude/skills/apply-remediations.md` to apply these fixes.\n\n"

        # Add recommended fix order
        content += """---

## Recommended Fix Order

1. **Fix Validation Drift (HIGH priority)**
   - Prevents invalid data from entering your system
   - Reduces security risks
   - Command: `claude "fix the validation drift issues"`

2. **Fix Contract Drift (MEDIUM priority)**
   - Ensures API responses match specification
   - Improves API consistency
   - Command: `claude "fix the contract drift issues"`

3. **Verify Fixes**
   - Re-run validation: `acv validate --spec <spec> --url <url>`
   - Target: 0 drift issues

---

## Using Claude Code CLI to Fix Issues

This repository now includes custom Claude Code skills to help you fix drift issues efficiently.

### Available Skills

- **fix-validation-drift**: Automatically add input validation to endpoints
- **fix-contract-drift**: Fix response schema mismatches
- **apply-remediations**: Apply AI-generated remediation suggestions

### Example Usage

```bash
# Ask Claude to fix validation issues
claude "fix the validation drift issues"

# Claude will:
# 1. Read the drift report
# 2. Detect your API framework
# 3. Generate appropriate validation code
# 4. Apply fixes to affected endpoints
# 5. Commit changes with descriptive message

# Ask Claude to apply specific remediations
claude "apply the remediation suggestions from ACV"

# Verify fixes
acv validate --spec <spec> --url <url>
```

---

## Detailed Reports

For complete analysis, see:
- JSON Report: `acv-reports/drift_report_*.json`
- Markdown Report: `acv-reports/drift_report_*.md`

---

## Notes

- Always review changes before committing
- Re-run ACV validation after applying fixes
- This file was auto-generated and will be updated on each ACV run
- Manual edits will be preserved (appended sections won't be overwritten)

---

*Generated by API Contract Validator v{self.config.metadata.version if hasattr(self.config, 'metadata') else '0.1.0'}*
"""

        # Write to file (append if exists)
        claude_md_path = repo_root / "CLAUDE.md"
        if claude_md_path.exists():
            logger.info(f"CLAUDE.md exists, appending new section")
            existing_content = claude_md_path.read_text()
            separator = f"\n\n---\n\n# ACV Update - {timestamp}\n\n"
            content = existing_content + separator + content
        else:
            logger.info(f"Creating new CLAUDE.md")

        claude_md_path.write_text(content)
        return claude_md_path

    def _generate_fix_validation_skill(
        self,
        drift_report: DriftReport,
        analysis_result: Optional[AnalysisResult],
        skills_dir: Path,
    ) -> Path:
        """Generate fix-validation-drift.md skill."""

        # Group issues by endpoint
        issues_by_endpoint = {}
        for issue in drift_report.validation_drift:
            if issue.endpoint_id not in issues_by_endpoint:
                issues_by_endpoint[issue.endpoint_id] = []
            issues_by_endpoint[issue.endpoint_id].append(issue)

        # Get affected endpoints summary
        affected_summary = []
        for endpoint_id, issues in sorted(issues_by_endpoint.items(), key=lambda x: len(x[1]), reverse=True)[:5]:
            affected_summary.append(f"- `{endpoint_id}`: {len(issues)} issues")

        content = f"""---
name: fix-validation-drift
description: Automatically fix validation drift issues detected by ACV
---

# Fix Validation Drift Issues

Automatically applies fixes for validation drift issues found in the ACV drift report.

## Context

**Total Validation Issues:** {len(drift_report.validation_drift)}
**Affected Endpoints:**
{chr(10).join(affected_summary)}

## When to Use

Invoke this skill when the user asks to:
- "fix the validation drift"
- "add input validation"
- "fix validation issues"
- "prevent invalid inputs"

## What This Skill Does

1. Loads the latest ACV drift report
2. Parses validation drift issues
3. Detects the API framework (Flask, FastAPI, Django, Express, etc.)
4. Generates appropriate validation code
5. Applies fixes to affected endpoints
6. Verifies fixes by re-running ACV
7. Commits changes with descriptive message

## Implementation Strategy

### Step 1: Load Latest Drift Report

```bash
# Find most recent drift report
REPORT=$(find . -name "drift_report_*.json" -type f -printf '%T@ %p\\n' 2>/dev/null | sort -rn | head -1 | cut -f2- -d" ")
```

### Step 2: Parse Validation Drift Issues

Extract validation drift issues and group by endpoint:

```python
import json
from collections import defaultdict

report = json.load(open(report_path))
validation_issues = report['drift_details']['validation_drift']

# Group by endpoint
by_endpoint = defaultdict(list)
for issue in validation_issues:
    by_endpoint[issue['endpoint_id']].append(issue)
```

### Step 3: Detect API Framework

Search for framework indicators:

**Python Frameworks:**
- Flask: `from flask import`, `@app.route`
- FastAPI: `from fastapi import`, `@app.get`, `@app.post`
- Django: `from django`, `django.http`, `urls.py`

**JavaScript Frameworks:**
- Express: `const express = require`, `app.get(`, `app.post(`
- NestJS: `@Controller`, `@Post`, `@Get`

**Other:**
- Ruby on Rails: `class ... < ApplicationController`
- Go: `func (.*) ServeHTTP`

### Step 4: Generate Validation Code

#### For Flask + Marshmallow:

```python
from flask import Flask, request, jsonify
from marshmallow import Schema, fields, validate, ValidationError

# Generate schema from OpenAPI spec
class {{ResourceName}}InputSchema(Schema):
    # Example for POST /users validation drift
    email = fields.Email(required=True)
    name = fields.Str(required=True, validate=validate.Length(min=1, max=100))
    age = fields.Int(validate=validate.Range(min=0, max=150))

schema = {{ResourceName}}InputSchema()

@app.route("{{path}}", methods=["{{method}}"])
def {{handler_name}}():
    try:
        # Add validation before existing logic
        validated_data = schema.load(request.get_json())
    except ValidationError as err:
        return jsonify({{"error": "validation_failed", "details": err.messages}}), 422

    # PRESERVE existing handler logic below
    # ... original code ...
```

#### For FastAPI + Pydantic:

```python
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field, EmailStr, validator

class {{ResourceName}}Input(BaseModel):
    email: EmailStr
    name: str = Field(..., min_length=1, max_length=100)
    age: int = Field(None, ge=0, le=150)

    @validator('age')
    def validate_age(cls, v):
        if v is not None and (v < 0 or v > 150):
            raise ValueError('Age must be between 0 and 150')
        return v

@app.post("{{path}}")
def {{handler_name}}(data: {{ResourceName}}Input):
    # Validation happens automatically via Pydantic
    # PRESERVE existing handler logic
    # ... original code ...
```

#### For Express + Joi:

```javascript
const Joi = require('joi');

const {{resourceName}}Schema = Joi.object({{
  email: Joi.string().email().required(),
  name: Joi.string().min(1).max(100).required(),
  age: Joi.number().integer().min(0).max(150)
}});

app.post('{{path}}', (req, res) => {{
  // Add validation before existing logic
  const {{ error, value }} = {{resourceName}}Schema.validate(req.body);

  if (error) {{
    return res.status(422).json({{
      error: 'validation_failed',
      details: error.details
    }});
  }}

  // PRESERVE existing handler logic
  // ... original code ...
}});
```

### Step 5: Apply Fixes

For each affected endpoint:

1. **Find handler file**: Use grep to locate endpoint path definition
2. **Read handler code**: Load the current implementation
3. **Detect framework**: Identify which framework is being used
4. **Generate validation**: Create appropriate validation code
5. **Insert validation**: Add validation BEFORE business logic
6. **Preserve logic**: Keep all existing functionality
7. **Format code**: Maintain consistent code style

**Important Rules:**
- ❌ NEVER delete existing business logic
- ✅ ONLY add validation layer at the beginning
- ✅ Preserve all error handling
- ✅ Match existing code style and indentation
- ✅ Import required validation libraries

### Step 6: Verify Fixes

```bash
# Re-run ACV validation
acv validate --spec {{spec_path}} --url {{api_url}}

# Check results
python3 << 'EOF'
import json
from pathlib import Path

# Find latest report
reports = sorted(Path('.').glob('**/drift_report_*.json'), key=lambda p: p.stat().st_mtime)
if reports:
    report = json.load(reports[-1].open())
    remaining = len(report['drift_details']['validation_drift'])
    fixed = {len(drift_report.validation_drift)} - remaining

    print(f"\\n✅ Fixed {{fixed}} validation drift issues!")
    print(f"📊 {{remaining}} issues remaining\\n")

    if remaining == 0:
        print("🎉 All validation drift issues resolved!")
EOF
```

### Step 7: Commit Changes

```bash
# Stage modified files
git add {{modified_files}}

# Generate descriptive commit message
git commit -m "fix: add input validation to resolve ACV drift

- Added validation schemas for affected endpoints
- Fixes {len(drift_report.validation_drift)} validation drift issues
- Prevents invalid data from entering the system

Affected endpoints:
{chr(10).join(f'  - {endpoint}' for endpoint in sorted(issues_by_endpoint.keys())[:5])}

ACV Report: {{report_path}}"
```

## Example Interaction

```
User: "fix the validation drift issues"

Claude:
🔍 Analyzing validation drift report...

Found {len(drift_report.validation_drift)} validation drift issues across {len(issues_by_endpoint)} endpoint(s).

📦 Detecting framework... Flask detected

🔧 Generating validation schemas...
   ✓ UserInputSchema for POST /users

📝 Applying fixes...
   ✓ Modified src/api/users.py
   ✓ Added marshmallow validation
   ✓ Preserved existing business logic

✅ Running verification...
   acv validate --spec openapi/api.yaml --url http://localhost:8000

   Fixed: {len(drift_report.validation_drift)} issues
   Remaining: 0 issues

🎉 All validation drift resolved!

📦 Committing changes...
   git commit -m "fix: add input validation..."

✅ Done! Your API now properly validates inputs.
```

## Notes

- This skill preserves all existing code
- Only adds validation layer at the beginning of handlers
- Requires appropriate validation library (marshmallow, pydantic, joi, etc.)
- If library is missing, Claude will suggest installation command
- Always review generated code before committing

---

*Auto-generated by API Contract Validator*
"""

        skill_path = skills_dir / "fix-validation-drift.md"
        skill_path.write_text(content)
        logger.info(f"Generated fix-validation-drift skill at {skill_path}")
        return skill_path

    def _generate_fix_contract_skill(
        self,
        drift_report: DriftReport,
        analysis_result: Optional[AnalysisResult],
        skills_dir: Path,
    ) -> Path:
        """Generate fix-contract-drift.md skill."""

        # Group contract issues by endpoint
        issues_by_endpoint = {}
        for issue in drift_report.contract_drift:
            if issue.endpoint_id not in issues_by_endpoint:
                issues_by_endpoint[issue.endpoint_id] = []
            issues_by_endpoint[issue.endpoint_id].append(issue)

        content = f"""---
name: fix-contract-drift
description: Fix contract drift issues (response schema mismatches)
---

# Fix Contract Drift Issues

Automatically fixes response schema mismatches detected by ACV.

## Context

**Total Contract Issues:** {len(drift_report.contract_drift)}
**Affected Endpoints:** {len(issues_by_endpoint)}

## When to Use

Invoke when user asks to:
- "fix the contract drift"
- "fix response schema mismatches"
- "make responses match the spec"

## What This Skill Does

1. Identifies response schema mismatches
2. Determines fix strategy for each issue type
3. Modifies response serializers
4. Verifies fixes with ACV

## Issue Types & Fixes

### Missing Required Field

**Problem:** API response is missing a field required by the spec

**Fix Strategy:**
- Add field to response serializer
- Ensure field is populated from data model
- Return appropriate default if data unavailable

```python
# Example fix for Flask
response_data = {{
    "id": user.id,
    "email": user.email,     # ← Add missing field
    "name": user.name,
    # ... other fields
}}
```

### Type Mismatch

**Problem:** Field has wrong type (e.g., int instead of string)

**Fix Strategy:**
- Convert to correct type in serializer
- Or update OpenAPI spec if current type is correct

```python
# Fix: Convert to spec-expected type
response_data = {{
    "user_id": str(user.id),  # Convert int to string if spec expects string
    "age": int(user.age),     # Convert string to int if spec expects int
}}
```

### Extra Fields

**Problem:** Response includes fields not in spec

**Fix Strategy:**
- Remove sensitive/internal fields
- Or add to spec if field should be public

```python
# Fix: Use explicit serializer (don't return all fields)
class UserSerializer:
    def serialize(self, user):
        return {{
            "id": user.public_id,
            "name": user.name,
            # DON'T include: user.internal_id, user.debug_info
        }}
```

## Implementation

Follow similar pattern to fix-validation-drift:
1. Parse contract drift issues from report
2. Group by endpoint and issue type
3. Apply appropriate fix for each issue type
4. Verify with ACV
5. Commit changes

---

*Auto-generated by API Contract Validator*
"""

        skill_path = skills_dir / "fix-contract-drift.md"
        skill_path.write_text(content)
        logger.info(f"Generated fix-contract-drift skill at {skill_path}")
        return skill_path

    def _generate_apply_remediations_skill(
        self,
        analysis_result: AnalysisResult,
        skills_dir: Path,
        drift_report: DriftReport,
    ) -> Path:
        """Generate apply-remediations.md skill."""

        content = f"""---
name: apply-remediations
description: Apply AI-generated remediation suggestions from ACV
---

# Apply ACV Remediation Suggestions

Executes specific code fixes suggested by ACV's AI analysis.

## Context

**Available Remediations:** {len(analysis_result.remediations)}

## When to Use

Invoke when user asks to:
- "apply the remediation suggestions"
- "use ACV's recommendations"
- "apply the AI-suggested fixes"

## What This Skill Does

1. Loads AI-generated remediation suggestions
2. Shows each suggestion with priority and effort estimate
3. Applies fixes interactively or in batch
4. Verifies with ACV

## Workflow

### Step 1: Load Remediations

```python
import json

report = json.load(open(latest_drift_report_path))
ai_analysis = report.get('ai_analysis', {{}})
remediations = ai_analysis.get('remediations', [])

print(f"Found {{len(remediations)}} AI-generated remediation(s)")
```

### Step 2: Display Remediations

For each remediation:

```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Remediation #1: {{title}}

Endpoint: {{endpoint_id}}
Priority: {{priority}}
Estimated Effort: {{estimated_effort}}

Description:
{{description}}

Implementation Steps:
1. {{step1}}
2. {{step2}}
3. {{step3}}

Code Example:
```{{language}}
{{code_example}}
```

Apply this fix? [y/n/view/skip/quit]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

### Step 3: Interactive Application

**Options:**
- `y` (yes): Apply this fix immediately
- `n` (no): Skip this fix
- `view`: Show detailed diff before applying
- `skip`: Skip and move to next
- `quit`: Stop and exit

### Step 4: Apply Fix

When user confirms:

1. Parse code_example from remediation
2. Identify target file (from endpoint_id)
3. Apply changes using Edit tool
4. Show diff for review
5. Run tests if available
6. Continue to next remediation

### Step 5: Verify All Fixes

```bash
# After applying all remediations
acv validate --spec {{spec}} --url {{url}}

# Report results
python3 << 'EOF'
import json
from pathlib import Path

reports = sorted(Path('.').glob('**/drift_report_*.json'), key=lambda p: p.stat().st_mtime)
if reports:
    report = json.load(reports[-1].open())
    total = report['drift_summary']['total_issues']

    print(f"\\n✅ Validation complete!")
    print(f"📊 {{total}} drift issue(s) remaining\\n")

    if total == 0:
        print("🎉 All drift issues resolved!")
EOF
```

### Step 6: Commit Changes

```bash
git add {{modified_files}}
git commit -m "fix: apply ACV remediation suggestions

Applied {{applied_count}} AI-generated fixes:
{{list_of_applied_remediations}}

ACV Report: {{report_path}}"
```

## Example Interaction

```
User: "apply the remediation suggestions"

Claude:
🤖 Loading AI-generated remediations from ACV report...

Found {len(analysis_result.remediations)} remediation(s)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Remediation #1: Add input validation middleware

Endpoint: POST /users
Priority: HIGH
Estimated Effort: LOW (1-2 hours)

Description:
Add marshmallow validation schema to prevent invalid
inputs from reaching the business logic.

[Shows code example]

Apply this fix? [y/n/view/skip/quit]: y

✅ Applied! Modified src/api/users.py

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[Continues for remaining remediations...]

✅ Applied 3 of {len(analysis_result.remediations)} remediations

🔍 Verifying fixes...
   acv validate --spec openapi/api.yaml --url http://localhost:8000

   Remaining issues: 0

🎉 All suggested fixes applied and verified!

📦 Committing changes...
   git commit -m "fix: apply ACV remediation suggestions..."
```

## Notes

- Each remediation includes AI-generated code examples
- Priority helps determine fix order
- Effort estimates help with sprint planning
- Interactive mode allows selective application
- Always verify fixes with ACV after applying

---

*Auto-generated by API Contract Validator*
"""

        skill_path = skills_dir / "apply-remediations.md"
        skill_path.write_text(content)
        logger.info(f"Generated apply-remediations skill at {skill_path}")
        return skill_path
